//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoboWeb {
    
    
    public partial class _Default {
        
        /// <summary>
        /// checkECotoveloEmRepouso control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkECotoveloEmRepouso;
        
        /// <summary>
        /// checkECotoveloLevementeContraido control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkECotoveloLevementeContraido;
        
        /// <summary>
        /// checkECotoveloContraido control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkECotoveloContraido;
        
        /// <summary>
        /// checkECotoveloFortementeContraido control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkECotoveloFortementeContraido;
        
        /// <summary>
        /// checkEPulsoRotacaoMenosNoventa control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkEPulsoRotacaoMenosNoventa;
        
        /// <summary>
        /// checkEPulsoRotacaoMenosQuarentaCinco control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkEPulsoRotacaoMenosQuarentaCinco;
        
        /// <summary>
        /// checkEPulsoRepouso control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkEPulsoRepouso;
        
        /// <summary>
        /// checkEPulsoRotacaoQuarentaCinco control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkEPulsoRotacaoQuarentaCinco;
        
        /// <summary>
        /// checkEPulsoRotacaoNoventa control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkEPulsoRotacaoNoventa;
        
        /// <summary>
        /// checkEPulsoRotacaoCemTrintaCinco control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkEPulsoRotacaoCemTrintaCinco;
        
        /// <summary>
        /// checkEPulsoRotacaoCemOitenta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkEPulsoRotacaoCemOitenta;
        
        /// <summary>
        /// checkDCotoveloEmRepouso control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkDCotoveloEmRepouso;
        
        /// <summary>
        /// checkDCotoveloLevementeContraido control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkDCotoveloLevementeContraido;
        
        /// <summary>
        /// checkDCotoveloContraido control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkDCotoveloContraido;
        
        /// <summary>
        /// checkDCotoveloFortementeContraido control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkDCotoveloFortementeContraido;
        
        /// <summary>
        /// checkDPulsoRotacaoMenosNoventa control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkDPulsoRotacaoMenosNoventa;
        
        /// <summary>
        /// checkDPulsoRotacaoMenosQuarentaCinco control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkDPulsoRotacaoMenosQuarentaCinco;
        
        /// <summary>
        /// checkDPulsoRepouso control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkDPulsoRepouso;
        
        /// <summary>
        /// checkDPulsoRotacaoQuarentaCinco control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkDPulsoRotacaoQuarentaCinco;
        
        /// <summary>
        /// checkDPulsoRotacaoNoventa control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkDPulsoRotacaoNoventa;
        
        /// <summary>
        /// checkDPulsoRotacaoCemTrintaCinco control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkDPulsoRotacaoCemTrintaCinco;
        
        /// <summary>
        /// checkDPulsoRotacaoCemOitenta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkDPulsoRotacaoCemOitenta;
        
        /// <summary>
        /// checkCabecaRotacaoMenosNoventa control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkCabecaRotacaoMenosNoventa;
        
        /// <summary>
        /// checkCabecaRotacaoMenosQuarentaCinco control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkCabecaRotacaoMenosQuarentaCinco;
        
        /// <summary>
        /// checkCabecaRepouso control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkCabecaRepouso;
        
        /// <summary>
        /// checkCabecaRotacaoQuarentaCinco control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkCabecaRotacaoQuarentaCinco;
        
        /// <summary>
        /// checkCabecaRotacaoNoventa control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkCabecaRotacaoNoventa;
        
        /// <summary>
        /// checkCabecaParaCima control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkCabecaParaCima;
        
        /// <summary>
        /// checkInclinacaoCabecaRepouso control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkInclinacaoCabecaRepouso;
        
        /// <summary>
        /// checkCabecaParaBaixo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox checkCabecaParaBaixo;
    }
}
